server:
  port: 8004

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.winner.microservice.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: micro-service-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb04?serverTimezone=UTC
    username: root
    password: 12345678
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka,
                    http://eureka7003.com:7003/eureka, http://eureka7004.com:7004/eureka"
  instance:
    instance-id: micro-service-hystrix-dept-8004
    prefer-ip-address: true

logging:
  level:
    web: debug

info:
  app:
    name: MyMicroServiceTest
    domain: https://www.baidu.com

# 暴露所有的 actuator 访问路径
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
