server:
  port: 81

spring:
  application:
    name: micro-service-consumer-dept-81

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka,
                    http://eureka7003.com:7003/eureka, http://eureka7004.com:7004/eureka"

# 为特定服务指定自定义的负载均衡策略
MICRO-SERVICE-PROVIDER-DEPT:
  ribbon:
    NFLoadBalancerRuleClassName: com.winner.myrule.MySelfRule

logging:
  level:
    web: debug
