server:
  port: 7001

spring:
  application:
    name: micro-service-eureka-7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      defaultZone: "http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/,
                    http://eureka7004.com:7004/eureka/"
#     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
