spring:
  profiles:
  active:
    - dev
---
server:
  port: 8005
spring:
  profiles: dev
  application:
    name: micro-service-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB05?serverTimezone=UTC
    username: root
    password: 12345678
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.winner.microservice.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/,
                    http://eureka7003.com:7003/eureka/, http://eureka7004.com:7004/eureka/"
  instance:
    instance-id: micro-service-config-client-dept-dev
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
server:
  port: 8005
spring:
  profiles: test
  application:
    name: micro-service-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB05?serverTimezone=UTC
    username: root
    password: 12345678
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.winner.microservice.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/,
                    http://eureka7003.com:7003/eureka/, http://eureka7004.com:7004/eureka/"
  instance:
    instance-id: micro-service-config-client-dept-test
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
