spring:
  profiles:
    active:
    - dev
---
server:
  port: 7004
spring:
  profiles: dev
  application:
    name: micro-service-config-client-eureka
eureka:
  instance:
    hostname: eureka7004.com
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/,
                    http://eureka7003.com:7003/eureka/"
---
server:
  port: 7004
spring:
  profiles: test
  application:
    name: micro-service-config-client-eureka
eureka:
  instance:
    hostname: eureka7004.com
  client:
    register-with-eureka: false #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/,
                    http://eureka7003.com:7003/eureka/"
